//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_QKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOrder
    {
        public int ODID { get; set; }
        public int StaffOrderID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual StaffOrder StaffOrder { get; set; }
    }
}
