//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_QKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CreditCardID { get; set; }
        public int PaymentID { get; set; }
        public string CreditCardName { get; set; }
        public string CreditBank { get; set; }
        public string HashCreditNumber { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
