//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_QKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> BasicSalaryID { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual BasicSalary BasicSalary { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Position Position { get; set; }
        public virtual StaffChef StaffChef { get; set; }
        public virtual StaffOrder StaffOrder { get; set; }
        public virtual StaffWareHouse StaffWareHouse { get; set; }
        public virtual PersonnelFile PersonnelFile { get; set; }
    }
}
